// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYfo2MJOMSxvFAcdyTQrg2zPm28lNvhlQ',
    appId: '1:709643947456:web:b6c9cef93da7a50c64cc25',
    messagingSenderId: '709643947456',
    projectId: 'find-my-spot-5ff45',
    authDomain: 'find-my-spot-5ff45.firebaseapp.com',
    storageBucket: 'find-my-spot-5ff45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPJgWR0B53ZBqic5QzRq2b-M-BimRcrNs',
    appId: '1:709643947456:android:e6624a02e8283a1a64cc25',
    messagingSenderId: '709643947456',
    projectId: 'find-my-spot-5ff45',
    storageBucket: 'find-my-spot-5ff45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBotdg0M0azkBx3pdYkgCSlJCEOOYmO2RY',
    appId: '1:709643947456:ios:1c1cbe84f9864a7a64cc25',
    messagingSenderId: '709643947456',
    projectId: 'find-my-spot-5ff45',
    storageBucket: 'find-my-spot-5ff45.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBotdg0M0azkBx3pdYkgCSlJCEOOYmO2RY',
    appId: '1:709643947456:ios:1c1cbe84f9864a7a64cc25',
    messagingSenderId: '709643947456',
    projectId: 'find-my-spot-5ff45',
    storageBucket: 'find-my-spot-5ff45.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYfo2MJOMSxvFAcdyTQrg2zPm28lNvhlQ',
    appId: '1:709643947456:web:8b7f4d38be6ebe4e64cc25',
    messagingSenderId: '709643947456',
    projectId: 'find-my-spot-5ff45',
    authDomain: 'find-my-spot-5ff45.firebaseapp.com',
    storageBucket: 'find-my-spot-5ff45.firebasestorage.app',
  );

}